# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cd6e98faef1a420846ed3d60890cd376a04eda368874ede1aa5f951ff2c45e3eed7e6df2a405f8cdab69cc7b4e216b3c73efc5e31180c34dd73c75259d3a1d5f

test:
  secret_key_base: 788017467248ee4e1dfa1489668abdc126d34ffb6658ca7940130ac9092bbcc5f5b031c00c85f326b45a3fc88d7ebc5fb571e82826093387f654c14565d31138

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
